# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odigos < Formula
  desc "Odigos CLI Utility"
  homepage "https://odigos.io"
  version "1.34.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odigos-io/odigos/releases/download/v1.34.3/cli_1.34.3_darwin_amd64.tar.gz"
      sha256 "b6979538bb5364d9d1464dfb2d8e433607633ab753cfccb6b257536688452e02"

      define_method(:install) do
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odigos-io/odigos/releases/download/v1.34.3/cli_1.34.3_darwin_arm64.tar.gz"
      sha256 "aeafdd2d364804319fa2975a9232944e85fae9b430e9cc2f2a7d2cb1d282ac0a"

      define_method(:install) do
        bin.install "odigos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.34.3/cli_1.34.3_linux_amd64.tar.gz"
      sha256 "b656b8ed31e89613cc03419fc2067a145629ef9d8a85ba764ca793b6a528b508"
      define_method(:install) do
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.34.3/cli_1.34.3_linux_arm64.tar.gz"
      sha256 "872e6bb1aa851674bfb4eb1a6540cc0f36f90ed8d3a760d34aa4e55328ca0015"
      define_method(:install) do
        bin.install "odigos"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing Odigos CLI! Please run `odigos install` to install Odigos in your Kubernetes cluster.
    EOS
  end
end
