# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odigos < Formula
  desc "Odigos CLI Utility"
  homepage "https://odigos.io"
  version "1.0.32"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/keyval-dev/odigos/releases/download/v1.0.32/cli_1.0.32_darwin_arm64.tar.gz"
      sha256 "ad52b38a093b77b293bfe5e4582e616834386fe5b8cee8029214b9af5ea17694"

      def install
        bin.install "odigos"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/keyval-dev/odigos/releases/download/v1.0.32/cli_1.0.32_darwin_amd64.tar.gz"
      sha256 "e3d180250428253fa0c8dbbb0244f602ac19d71a18bde611277409f39c173c5b"

      def install
        bin.install "odigos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keyval-dev/odigos/releases/download/v1.0.32/cli_1.0.32_linux_arm64.tar.gz"
      sha256 "a46537d5edefc907675de7f2432615aeab36d988fa32bdcd251f3af75b46f959"

      def install
        bin.install "odigos"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/keyval-dev/odigos/releases/download/v1.0.32/cli_1.0.32_linux_amd64.tar.gz"
      sha256 "d3c2b9ae728f28f2cd47c68be2e01eb8d4af1211cae95f643cf9bc42a88705a5"

      def install
        bin.install "odigos"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing Odigos CLI! Please run `odigos install` to install Odigos in your Kubernetes cluster.
    EOS
  end
end
